import { ArrowRight, ArrowUpRight, Asterisk } from 'lucide-react';
import { Link } from 'react-router-dom';
import { Image, Reveal } from '../components/UI';
import { useTitle } from '../lib/api';
import { editorialImages } from './Home';

export function About() {
  useTitle('Our story');
  return <>
    <section className="about-hero page-shell"><p className="eyebrow">A PLACE. A FEELING. A POINT OF VIEW.</p><h1>Some things stay with you.<br /><em>Even when you move.</em></h1><div className="about-intro"><span className="about-mark">क</span><p>The texture of a lane. The pause before the city wakes. The way the familiar finds a new meaning.<br /><br />URBAN KASHI begins with that feeling.</p></div></section>
    <div className="about-photo">
      <Image src={editorialImages.story} alt="Original riverside illustration inspired by Kashi, not a photograph or depiction of an exact real location" />
      <span>ORIGINAL ILLUSTRATION / KASHI-INSPIRED RIVERSIDE</span>
    </div>
    <section className="section about-body"><Reveal className="story-grid"><div><p className="eyebrow">OUR POINT OF VIEW</p><h2>Rooted.<br /><em>Not standing still.</em></h2></div><div className="prose"><p>We think a wardrobe can hold more than one version of you. The person at ease in an old neighbourhood and the person curious about a new city. Neither needs to dress like someone else.</p><p>Our menswear concept brings together familiar silhouettes and an editorial eye: shirts, T-shirts, trousers, kurtas and layers, with room to mix them in your own way.</p><p>Kashi is our creative reference, not a claim about where each garment is made. We don’t invent a founding history, artisan partnerships or sourcing promises. Product-specific facts belong in the product details, where you can actually use them.</p><Link to="/shop" className="text-link">Find your own expression<ArrowUpRight size={18} /></Link></div></Reveal></section>
    <section className="about-manifesto"><Asterisk size={55} strokeWidth={1} /><h2>Less about fitting in.<br /><em>More about feeling like you.</em></h2><p>OLD SOUL. NEW PERSPECTIVE.</p></section>
    <section className="section narrow-section prose"><h2>A note on this storefront.</h2><p>This is an independent ecommerce demo, not linked to a point-of-sale system. Inventory and Unsplash photography are placeholders. Editorial images illustrate a mood and may not depict the exact listed garment. CSV imports do not automatically synchronise POS stock; website stock must be allocated separately.</p><p>Accounts and orders use the connected API. Cash on delivery is the default. Optional Razorpay checkout is available only when the server enables it; current availability and test mode are shown at checkout. Real-key gateway operation has not been verified. Demo orders do not promise real-world fulfilment.</p><Link to="/shipping" className="text-link">Read the shipping draft<ArrowRight size={17} /></Link></section>
  </>;
}
export function Shipping() {
  useTitle('Shipping & returns');
  return <div className="page-shell policy-page"><div className="page-heading"><p className="eyebrow">GOOD TO KNOW / POLICY DRAFT</p><h1>A little <em>clarity.</em></h1><p>Shipping, payment & returns</p></div><div className="notice-panel">This is a demo policy draft, not a verified live-store fulfilment promise. Final operating terms and support contact details must be published before real trading.</div><div className="prose">
    <h2>Shipping charges</h2><p>Shipping is complimentary when the merchandise subtotal is ₹2,499 or more. Below that threshold, shipping is ₹99. Amounts are in integer Indian rupees. Your final total is calculated and validated by the server when you place an order.</p>
    <h2>Delivery & service area</h2><p>The checkout accepts an Indian delivery address with a six-digit PIN code and a ten-digit mobile number. A valid address format does not verify courier serviceability. Delivery estimates, courier partners, tracking and actual dispatch are not configured for this demo.</p>
    <h2>Payment</h2><p>Cash on delivery remains the default. Online payment is optional and disabled unless the server has enabled Razorpay. Checkout shows the current availability, unavailable reason and test / live mode. UPI, cards, netbanking, wallets, EMI and pay later depend on provider rules and merchant eligibility; not every method is always available. Test mode is not a real paid purchase. Real-key gateway operation has not been verified for this integration.</p>
    <p>Razorpay is loaded only when you choose online payment and continue. Enter payment credentials only in its hosted checkout, never in the local address form. The server determines the payment amount and verifies the result. A browser callback or an order record alone is not proof of payment or dispatch.</p>
    <h2>Pending online orders</h2><p>An online order is recorded and stock reserved before payment is confirmed. If the modal closes, payment fails or the network disconnects, check the existing order in your account and use “Check payment status” before paying again. The bag is kept while payment is pending; it does not mean that a second order is needed. Contact the store with the order ID if unresolved. Resume payment is not currently available from order detail.</p>
    <h2>Order updates</h2><p>Sign in to your account to see your orders, payment state and fulfilment status separately. Statuses can be placed, confirmed, shipped, delivered or cancelled. Unpaid online orders cannot be confirmed or shipped. The demo has no automated email or SMS delivery confirmation.</p>
    <h2>Returns, exchanges & cancellation</h2><p>A return window, eligibility rules, refund process and customer support channel have not been finalised. Self-service returns, exchanges and cancellation are not available. “Refund required” means the store must manually process and verify a refund in the payment provider dashboard; it does not mean a refund has completed. Do not treat demo orders as purchases with guaranteed fulfilment or a published commercial returns policy.</p>
    <h2>Before real-world use</h2><p>The store operator needs to verify gateway configuration and settlement, publish business details, a working support contact, service areas, dispatch estimates and legally reviewed consumer policies. This draft does not limit any rights under applicable law.</p><Link className="button" to="/account">View your orders<ArrowRight size={17} /></Link>
  </div></div>;
}
export function Privacy() {
  useTitle('Privacy');
  return <div className="page-shell policy-page">
    <div className="page-heading"><p className="eyebrow">GOOD TO KNOW / POLICY DRAFT</p><h1>Your details.<br /><em>Handled thoughtfully.</em></h1><p>A transparent overview of this demo’s data flows.</p></div>
    <div className="notice-panel">Draft only. This is not a completed legal privacy notice. Avoid using real personal details or a password you use elsewhere when testing.</div>
    <div className="prose">
      <h2>Accounts & orders</h2><p>Registration sends your name, email and password to the store API. Checkout sends the selected product IDs, sizes, quantities and delivery details: name, phone, address, city, state and PIN code. Orders are linked to your authenticated account. Authorised store administrators can access customer information contained in orders.</p>
      <h2>Browser storage & sessions</h2><p>The bag and wishlist are stored in this browser’s local storage and are not an account-synchronised wishlist. Sign-out does not clear those lists. Checkout stores temporary request signatures, retry keys and known order IDs in session storage to avoid duplicate orders. These include user ID, selected items, payment method and delivery details. Pending attempts remain for recovery; completed COD and server-verified paid attempts are removed when handled by checkout or payment reconciliation. Session storage normally expires when the browser tab session ends. Signing out does not remove pending recovery records from that tab.</p><p>Authentication uses the server’s same-origin session mechanism. The frontend sends requests with same-origin credentials; it does not store session tokens or password hashes in browser storage. Clear this site’s browser data to remove local bag, wishlist and checkout recovery data.</p>
      <h2>Locally served fonts & images</h2>
      <p>Default fonts are self-hosted using Fontsource, and all default demo photographs and the original Kashi-inspired riverside illustration are served locally by this storefront. Loading these default assets makes no third-party font or image requests, including to Google Fonts or Unsplash.</p>
      <p>Store administrators may optionally add external HTTPS image URLs. Only when those external images are loaded does your browser contact their providers, sharing network information such as your IP address and browser request details.</p>
      <h2>Optional payment gateway</h2><p>Cash on delivery does not load Razorpay. Only after you choose online payment and continue, and the server confirms it is configured, does the browser load Razorpay’s checkout script and contact its services. This shares network information such as your IP address and browser details. Continuing online also shares the current recipient name and phone and your account email for gateway prefill, as explained at checkout.</p><p>Payment credentials are entered in Razorpay, not the storefront’s local form. This frontend does not collect or store raw card, bank or UPI credentials. Gateway order and payment identifiers and the callback signature are sent to the store server for verification; callback signatures are not saved in browser storage. Orders show the server-recorded payment state, not an unverified browser success claim. Gateway processing is subject to the provider’s privacy terms. Real-key operation and final legal disclosures still require operator verification. There is no newsletter subscription or AI processing feature in this frontend.</p>
      <h2>Retention, access & deletion</h2><p>Data retention periods, the operator’s legal identity, a privacy contact and a verified data-access or deletion process have not been published. The account page does not currently offer account deletion. These details require confirmation before the store accepts real customer information.</p>
      <Link className="text-link" to="/account">Go to your account<ArrowRight size={17} /></Link>
    </div>
  </div>;
}
export function NotFound() { useTitle('Page not found'); return <div className="page-shell not-found"><p className="eyebrow">404 / A DIFFERENT TURN</p><h1>A little <em>off the map.</em></h1><p>This page doesn’t exist. There’s still plenty to discover.</p><Link className="button" to="/shop">Back to the collection<ArrowUpRight size={18} /></Link><Link className="text-link" to="/">Take me home<ArrowRight size={16} /></Link></div>; }